version: "3"

services:
  app:
    container_name: statlist
    build:
      context: ../
      dockerfile: ./docker/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
