name: Deployment tests
on:
  pull_request:
    branches: main
jobs:
  test_setup:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          check_interval: 10
          environment: Preview
  test_e2e:
    needs: test_setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install Node environnment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.14.2
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - name: Run server
        run: xvfb-run --auto-servernum pnpm run test
        env:
          CI: true
          NEXT_AUTH_URL: ${{ secrets.PREVIEW_URL }}
          PASSWORD: ${{secrets.PASSWORD}}
          USERNAME: ${{secrets.USERNAME}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          SPOTIFY_CLIENT_ID: ${{secrets.SPOTIFY_CLIENT_ID}}
          SPOTIFY_CLIENT_SECRET: ${{secrets.SPOTIFY_CLIENT_SECRET}}
      - name: Download trace of test
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
